version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Preparing Lambda code upload..."

  post_build:
    commands:
      - echo "Uploading raw lambda_function.py to S3..."
      - aws s3 cp lambda/lambda_function.py s3://lamda-code-bucket-azamcloud/lambda_function.py

artifacts:
  files:
    - lambda/lambda_function.py
  discard-paths: true
