AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ### Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LamdaS3ProcessingRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        
  FileProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code:
        S3Bucket: !ImportValue LamdaS3CodeBucketName
        S3Key: !ImportValue LamdaCodeName
      Timeout: 60
      Environment:
        Variables:
          SNS_TOPIC_ARN: !ImportValue SNSTopicName

  ### Permission for S3 to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FileProcessorLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !ImportValue FileUploadBucketArn

      Outputs:

  FileProcessorLambdaArn:
    Value: !GetAtt FileProcessorLambda.Arn
    Export:
      Name: FileProcessorLambdaArn
