AWSTemplateFormatVersion: '2010-09-09'

Resources:
  FileProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: !ImportValue IAMRoleName
      Runtime: python3.12
      Code:
        S3Bucket: !ImportValue LamdaS3CodeBucketName
        S3Key: !ImportValue LamdaCodeName
      Timeout: 60
      Environment:
        Variables:
          SNS_TOPIC_ARN: !ImportValue SNSTopicName

  ### Permission for S3 to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FileProcessorLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !ImportValue FileUploadBucketName

      
