AWSTemplateFormatVersion: '2010-09-09'

Resources:

  # S3 Bucket for Lambda Artifacts

 LambdaArtifactsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: lamda-code-bucket-azamcloud
    VersioningConfiguration:
     Status: Enabled
        
        
Outputs:
  LamdaS3CodeBucket:
    Value: !Ref LambdaArtifactsBucket
    Export:
     Name: LamdaS3CodeBucketName
