AWSTemplateFormatVersion: '2010-09-09'

Resources:

  ### S3 Bucket
  FileUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: file-upload-bucket-azamcloud

Outputs:

  FileUploadBucketName:
    Description: Name of the S3 bucket for file uploads
    Value: !GetAtt FileUploadBucket.Arn
    Export:
      Name: FileUploadBucketName
